### ISSUE TITLE
Actions artifacts

### ISSUE THREAD

**Issue by cassshh** [dutchhackers/actions-journey#5]
Perhaps we would like to save build artifacts in the action workflow (pipeline) itself;
https://github.com/actions/upload-artifact

And in turn use those artifacts to attach with release assets.

![image](https://user-images.githubusercontent.com/10263056/74657399-74816900-5190-11ea-85ab-61271c86fd29.png)

**Comment by mschilling** [comment]
Nice. Done 👌
